mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LastestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list , name='post_list'), #function based view 
    path('tag/<slug:tag_slug>/', views.post_list , name = 'list_post_by_tag'),
    #path('', views.PostListView.as_view(), name='post_list'), #class based view , that uses the generic ListView
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_details , name='post_details'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LastestPostsFeed(), name = 'post_feed'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = { #defined a sitemaps dictionary
    'posts' : PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# from .models import PublishedManager

# Create your models here.


# create a custom manager instance for published
class PublishedManager(models.Manager): 
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status = Post.Status.PUBLISHED)

class Post(models.Model):
    
    tags = TaggableManager()
    
    class Status(models.TextChoices):
        DRAFT = 'DF' , 'draft'
        PUBLISHED = 'PB' , 'published'
    
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(User, on_delete= models.CASCADE, related_name='blog_posts')
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, 
                              choices=Status.choices, default=Status.DRAFT)
    
     
    objects = models.Manager() # our default manager
    published = PublishedManager() # our custom manager
    
    class Meta:
        ordering = ['-publish'] # arranges the order of objected in decending order(newer published to older )
        indexes = [
            models.Index(fields=['publish']),
        ]
    
       
    
    def __str__(self):
        return self.title
    

    def get_absolute_url(self):
        return reverse("blog:post_details", args=[self.publish.year,
                                                  self.publish.month,
                                                  self.publish.day,
                                                  self.slug])
    
    

class Comment(models.Model):
    
    post = models.ForeignKey(Post, on_delete= models.CASCADE , related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(max_length=100)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"
    

mysite/blog/forms.py
from django import forms
from .models import Comment



class EmailPostForm(forms.Form):
    
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post , Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import ListView
from .forms import EmailPostForm , CommentForm
from django.core.mail import send_mail 
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count


# Create your views here.

def post_list(request, tag_slug=None):
    
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag , slug = tag_slug )
        post_list = post_list.filter(tags__in=[tag])
        
    
    #Pagination with 3 posts per page
    paginator = Paginator(post_list,3) # determine the number of posts to display on a page
    page_number = request.GET.get('page',1)#get the requested page number or default: 1 
    try:
        posts = paginator.page(page_number) 
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        #if the page_number is out of range deliver the last page of results
        posts = paginator.page(paginator.num_pages)  
    
    
    return render(request, 'blog/post/list.html', {'posts': posts, 'tag': tag})


def post_details(request,year,month,day,post):
    
    post = get_object_or_404(Post,status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    
    #QuerySet to retrieve all active comments for the post
    comments = post.comments.filter(active=True)
    
    # creating an instance of the comment form
    form = CommentForm()
    
    #List of of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                    .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags = Count('tags'))\
                    .order_by('-same_tags','-publish')[:4]
    
    
    return render(request, 'blog/post/details.html', {'post': post, 'comments': comments, 'form': form, 'similar_posts': similar_posts})

class PostListView(ListView): #class based view , inherited from ListView
    """
    Alternative to post_list view
    """
    
    queryset = Post.published.all()
    context_object_name= 'posts'
    paginate_by= 3
    template_name= 'blog/post/list.html'
    
    
    
def post_share(request, post_id):
    
    post = get_object_or_404(Post, id=post_id, status = Post.Status.PUBLISHED)
    sent = False
    
    
    if request.method == 'POST':
        #form was submitted
        
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form feilds passed validation
            cd = form.cleaned_data # captures the inputed data in a dictionary form (fields as keys and input as values)
            
            #send mail
            post_url = request.build_absolute_uri(post.get_absolute_url())
            
            subject = f"{cd['name']} recommended you read" \
                        f' "{post.title}"'
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comment']}"
                      
            send_mail(subject, message , 'dproject8420@gmail.com', [cd['to']])
            
            sent=True
            
    else:
        form = EmailPostForm()
        
    return render(request, 'blog/post/share.html', {'post': post, 'form': form , 'sent': sent})


@require_POST
def post_comment(request,post_id):
    
    post = get_object_or_404(Post, id = post_id, status = Post.Status.PUBLISHED )
    comment = None 
    
    
    form = CommentForm(data = request.POST)
    if form.is_valid():
        
        #create a comment object without saving to the database
        comment = form.save(commit=False)
        
        comment.post = post
        
        #save comment object to database
        comment.save()
        
    return render(request, 'blog/post/comment.html', {'post' : post, 'form':form, 'comment':comment})
    

mysite/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link  href="{% static "css/blog.css" %}" rel="stylesheet" >
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog</p>
         <p>I have written {% total_posts %} so far {% comment %} custom simple_tag to display the total number of post(post.published.count) {% endcomment %}

        <p>
            <a href="{% url "blog:post_feed" %}">
                Subcribe to my RSS feed
            </a>
        </p>
        
 {% comment %} custom inclusion_tag to display the latest post {% endcomment %}

    <h3>Latest Posts<h3>
        {% show_latest_posts 3 %}

    <h3>Most Commented Posts</h3>
    
    {% get_most_commented_posts as most_commented_posts %}

    <ul>

        {% for post in most_commented_posts %}

        <li> <a href="{{post.get_absolute_url}}"> {{ post.title }} </a> </li>


        {% endfor %}
    </ul>


    </div>


</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

mysite/blog/templates/blog/post/comment.html
    {% extends "blog/base.html" %}

    {% block title %} Add a comment  {% endblock %}

    {% block content %}
    
    {% if comment %}
        <h2> Your comment has been added</h2>
        <a href="{{ post.get_absolute_url }}"> Back to post</a>

    {% else %}

    {% include "blog/post/includes/comment_form.html" %}

    {% endif %} 


    {% endblock %}

mysite/blog/templates/blog/post/details.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %} {{post.title}}{% endblock %}

{% block content%}
<h1> {{post.title}}</h1>

<p class="date">
 Published: {{post.publish}}by {{post.author}}
</p> 

{% for tag in post.tags.all %}
   <a href="{% url "blog:list_post_by_tag" tag.slug %}">
      {{tag.name}}
   </a>
{% if not forloop.last %}, {% endif %}
{% endfor %}

 {{post.body|markdown|linebreaks }}


 <p>
    <a href="{% url "blog:post_share" post.id %}" > Share this post </a>
 </p>

 {% for similar_post in similar_posts %}
   <p>
      <a href="{{ similar_post.get_absolute_url }}" > {{similar_post}} </a>
   </p>
   
   {% empty %}
      <p>There is no Similar Post yet </p>
   
 {% endfor %}

 {% with comments.count as total_comments %}
 <h2 id="num_com">
   {{total_comments}} comment{{total_comments|pluralize}}
</h2>

 {% endwith %}

 {% for comment in comments %}
   <div class="comment">
      <p class="info" >
         Comment {{ forloop.counter }} by {{ comment.name}} {{ comment.created}}
      </p>
      {{comment.body|linebreaks}}
   </div>
   {% empty %}
   <p> There are no comments</p>

 {% endfor %}

 {% include "blog/post/includes/comment_form.html" %}

{% endblock %}

mysite/blog/templates/blog/post/includes/comment_form.html
<h2 id="com_header">Add a New Comment</h2>

<form class="com_form" action="{% url "blog:post_comment" post.id %}" method="post">
{{ form.as_p}}
{% csrf_token %}

<div class="col-12">
<input class="col" type="submit" value="Add comment">
</div>

</form>
<style>

    label { 
        float:left;
        clear:both;
        color:#333;
        margin-bottom:4px; 
    }
    input, textarea { 
        clear:both;
        float:left;
        margin:0 0 10px;
        background:#ededed;
        border:0;
        border-radius: 5px;
        padding:6px 10px;
        font-size:12px;
        resize: none;
        width: 50%;

        
    }

    input[type="text"]{
        width:40%;
    }

    input:focus{
       
        transition-duration: 0s;
        transition-timing-function: ease-in-out;
        transition-delay: 0.3s;

    }

</style>
{% comment %} input{
    padding: 5px 0;
    border-top : none;
    border-left : none;
    border-right : none;
    border-radius : 10px;
    width: 70%;

}
</style> {% endcomment %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>

    {% for post in latest_posts %}

    <li >

        <a href="{{ post.get_absolute_url }}" >{{post.title}} </a>
    </li>

    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
 
 {% block title %}My Blog {% endblock %}

{% block content%}
 <h1>My Blog</h1>

 {% if tag %}
    <h2> Post Tagged with "{{tag.name}}" </h2>
 {% endif %}

 {% for post in posts%}
    <h2>
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>
    
    </h2>
    <p class="tags" > 
        {% for tag in post.tags.all %}
            <a href=" {% url "blog:list_post_by_tag" tag.slug %}">
                {{tag.name}}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}

    </p>
    <p class="date">
        published: {{post.publish}} by {{ post.author}}
    </p>
    {{post.body|markdown|truncatewords_html:30|linebreaks}}

 {% endfor %}

 {% comment %} to switch to class based view, change 'posts' with 'page_obj' {% endcomment %}
 {% include 'pagination.html' with page=posts %} 

{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends 'blog/base.html'%}

{% block title %} Share a post{% endblock %}

{% block content %}
{% if sent %}
<h1> E-mail successfully sent !! </h1>
<p>
    {{post.title}} was successfully sent to {{form.cleaned_data.to}}
</p>
{% else %}
<h1 id="title"> Share "{{post.title}}" by email </h1>

<form method="post">
{% csrf_token %}
     
{% comment %} {{form.as_p}} {% endcomment %}

{% for field in form%}

<div class="forms">
{{feild.error}}
{{field.label_tag}} {{field}}
</div>

<style>
.forms{
    margin: 0 0 15px 0;

}

#title{
    font-weight: 700 !important;
}

input{
    padding: 5px 0;
    border-top : none;
    border-left : none;
    border-right : none;
    border-radius : 10px;
    width: 70%;

}

form{
    background-color: #ffe;
    border : 1px solid gray ;
    border-radius : 12px;
    width: 50%;
    padding: 15px;
    margin: 20px;
    {% comment %} justify-content: center; {% endcomment %}
    align-items: center;
    {% comment %} text-align: center; {% endcomment %}
    

}

.btn{
    width: 100%;
    border-radius: 10px;
    border: none;
}

</style>

{% endfor %}


<div class="d-grid gap-2">
    <input class="btn btn-primary" type="submit" value="send e-mail">
  </div>
</form>
{% endif %}

{% endblock %}

mysite/blog/templates/pagination.html
<div class="pagination" >

    <span class="step-links">

        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}" > Previous</a>
        {% endif %}

        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}.
        </span>

        {% if page.has_next %}
        <a href="?page={{page.next_page_number}}" >Next</a>
        {% endif %}

    </span>

</div>